'use strict';
var CONSTANT = {
	DEBUG: false,
	DEBUG_MUTE: true,
	DEBUG_SCENE: "title",
	DEBUG_STAGE_NO: 0,

	// RPGアツマールでのスコアボードID
	BOARD_ID_IN_ATSUMARU: 1,

	SCORE_TO_SHOW_OMAKE: 1000000000, // 10億

	// 時を止める時間
	TIMESTOP_FRAME: 600,
	// 時を止めるスペカを使えるようになるまでの時間
	TIME_TO_USE_TIMESTOP_FRAME: 20 * 60,

	// Pポイントの最大数
	P_MAX: 600,

	// 何フレームごとにPが回復するか
	FRAME_TO_RECOVER_P: 6,

	// ユニットの生成位置
	UNIT_GENERATED_AREA_LEFT_X:  100,
	UNIT_GENERATED_AREA_RIGHT_X: 200,
	UNIT_GENERATED_AREA_UP_Y:  400,
	UNIT_GENERATED_AREA_DOWN_Y: 450,

	// 敵の生成位置
	ENEMY_GENERATED_AREA_LEFT_X:  650,
	ENEMY_GENERATED_AREA_RIGHT_X: 700,
	ENEMY_GENERATED_AREA_UP_Y:  400,
	ENEMY_GENERATED_AREA_DOWN_Y: 450,

	// ユニット一覧
	UNIT_TYPE_BAZOOKA:     1,
	UNIT_TYPE_MAGICIAN:    2,
	UNIT_TYPE_MANDORAGORA: 3,
	UNIT_TYPE_MEISAKU:     4,
	UNIT_TYPE_MMD:         5,
	UNIT_TYPE_NORMAL1:     6,
	UNIT_TYPE_NORMAL2:     7,
	UNIT_TYPE_TEA:         8,
	UNIT_TYPE_TUPAI:       9,
	UNIT_TYPE_YOYOMU:      10,
};
module.exports = CONSTANT;
