'use strict';
var CONSTANT = {
	DEBUG: true,
	DEBUG_MUTE: false,
	DEBUG_SCENE: "battle",


	// Pポイントの最大数
	P_MAX: 600,

	// 何フレームごとにPが回復するか
	FRAME_TO_RECOVER_P: 60,

	// ユニットの生成位置
	UNIT_GENERATED_AREA_LEFT_X:  50,
	UNIT_GENERATED_AREA_RIGHT_X: 100,
	UNIT_GENERATED_AREA_UP_Y:  300,
	UNIT_GENERATED_AREA_DOWN_Y: 350,

	// 敵の生成位置
	ENEMY_GENERATED_AREA_LEFT_X:  650,
	ENEMY_GENERATED_AREA_RIGHT_X: 700,
	ENEMY_GENERATED_AREA_UP_Y:  300,
	ENEMY_GENERATED_AREA_DOWN_Y: 350,
};
module.exports = CONSTANT;
